language: python

python:
  - '3.6'
  - 'nightly'

sudo: false

cache: pip

install:
  - pip install --quiet --requirement requirements.txt

script:
  - ./manage.py makemigrations
  - ./manage.py migrate
  - ./manage.py test lists -v 2

notifications:
  email:
    on_success: change
    on_failure: change
